In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load IRIS Dataset

In [2]:
df = pd.read_csv("IRIS DATASET.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

# Create Categorical Groups for Sepal Length

In [4]:
# Create Groups for Sepal Length

df['sepal_length_group'] = pd.cut(
    df['sepal_length'],
    bins=3,
    labels=["Short", "Medium", "Long"]
)

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_length_group
0,5.1,3.5,1.4,0.2,Iris-setosa,Short
1,4.9,3.0,1.4,0.2,Iris-setosa,Short
2,4.7,3.2,1.3,0.2,Iris-setosa,Short
3,4.6,3.1,1.5,0.2,Iris-setosa,Short
4,5.0,3.6,1.4,0.2,Iris-setosa,Short

# Group Data and Calculate Statistics

In [5]:
# Group Data and Calculate Statistics

grouped_stats = df.groupby(
    'sepal_length_group',
    observed=False
)['petal_length'].agg([
    'mean',
    'median',
    'min',
    'max',
    'std'
])

grouped_stats

                        mean  median  min  max       std
sepal_length_group
Short               1.944068    1.50  1.0  4.5  0.993994
Medium              4.669014    4.80  1.2  6.0  0.889557
Long                5.880000    5.95  4.7  6.9  0.650991

# Create List of Petal Length Values

In [6]:
# Create List of Petal Length Values

group_lists = df.groupby(
    'sepal_length_group',
    observed=False
)['petal_length'].apply(list)

group_lists

sepal_length_group
Short     [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, ...
Medium    [1.2, 1.5, 1.7, 4.5, 4.6, 4.5, 4.7, 4.6, 4.2, ...
Long      [4.7, 4.9, 4.8, 5.9, 6.6, 6.3, 6.1, 5.5, 6.7, ...
Name: petal_length, dtype: object

# Get Unique Species Names

In [7]:
# Get Unique Species Names

species_list = df['species'].unique()

species_list

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# Calculate Mean for Each Species

In [8]:
# Calculate Mean for Each Species

for species in species_list:
    
    print("\nSpecies:", species)
    
    species_data = df[df['species'] == species]
    
    print(species_data.mean(numeric_only=True))

Species: Iris-setosa
sepal_length    5.006
sepal_width     3.418
petal_length    1.464
petal_width     0.244
dtype: float64

Species: Iris-versicolor
sepal_length    5.936
sepal_width     2.770
petal_length    4.260
petal_width     1.326
dtype: float64

Species: Iris-virginica
sepal_length    6.588
sepal_width     2.974
petal_length    5.552
petal_width     2.026
dtype: float64

# Calculate Standard Deviation

In [9]:
# Calculate Standard Deviation

for species in species_list:
    
    print("\nSpecies:", species)
    
    species_data = df[df['species'] == species]
    
    print(species_data.std(numeric_only=True))

Species: Iris-setosa
sepal_length    0.352490
sepal_width     0.381024
petal_length    0.173511
petal_width     0.107210
dtype: float64

Species: Iris-versicolor
sepal_length    0.516171
sepal_width     0.313798
petal_length    0.469911
petal_width     0.197753
dtype: float64

Species: Iris-virginica
sepal_length    0.635880
sepal_width     0.322497
petal_length    0.551895
petal_width     0.274650
dtype: float64

# Calculate Percentiles

In [10]:
# Calculate Percentiles

for species in species_list:
    
    print("\nSpecies:", species)
    
    species_data = df[df['species'] == species]
    
    print(
        species_data.quantile(
            [0.25, 0.50, 0.75],
            numeric_only=True
        )
    )

Species: Iris-setosa
      sepal_length  sepal_width  petal_length  petal_width
0.25           4.8        3.125         1.400          0.2
0.50           5.0        3.400         1.500          0.2
0.75           5.2        3.675         1.575          0.3

Species: Iris-versicolor
      sepal_length  sepal_width  petal_length  petal_width
0.25           5.6        2.525          4.00          1.2
0.50           5.9        2.800          4.35          1.3
0.75           6.3        3.000          4.60          1.5

Species: Iris-virginica
      sepal_length  sepal_width  petal_length  petal_width
0.25         6.225        2.800         5.100          1.8
0.50         6.500        3.000         5.550          2.0
0.75         6.900        3.175         5.875          2.3

In [11]:
print("Mean for all species:")

df.groupby('species').mean(numeric_only=True)

Mean for all species:

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [12]:
print("Standard Deviation for all species:")

df.groupby('species').std(numeric_only=True)

Standard Deviation for all species:

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa          0.352490     0.381024      0.173511     0.107210
Iris-versicolor      0.516171     0.313798      0.469911     0.197753
Iris-virginica       0.635880     0.322497      0.551895     0.274650

In [13]:
print("Quantiles (0.25, 0.50, 0.75) for all species:")

df.groupby('species').quantile(
    [0.25, 0.50, 0.75],
    numeric_only=True
)

Quantiles (0.25, 0.50, 0.75) for all species:

                      sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa     0.25         4.800        3.125         1.400          0.2
                0.50         5.000        3.400         1.500          0.2
                0.75         5.200        3.675         1.575          0.3
Iris-versicolor 0.25         5.600        2.525         4.000          1.2
                0.50         5.900        2.800         4.350          1.3
                0.75         6.300        3.000         4.600          1.5
Iris-virginica  0.25         6.225        2.800         5.100          1.8
                0.50         6.500        3.000         5.550          2.0
                0.75         6.900        3.175         5.875          2.3