In [34]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

# Step 1: Locate Open-Source Dataset

## Dataset Name
Iris Dataset

## Dataset Source URL
https://www.kaggle.com/datasets/uciml/iris

## Description
The Iris dataset is a famous dataset used for machine learning and data analysis.
It contains measurements of iris flowers from three different species:
1. Iris-setosa
2. Iris-versicolor
3. Iris-virginica

The dataset contains the following features:
- Sepal Length
- Sepal Width
- Petal Length
- Petal Width
- Species

# Step 2: Load Dataset into Pandas DataFrame

In [36]:
df = pd.read_csv("Iris.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

# Display First Five Records of Dataset

In [37]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Step 3: Check Dimensions of Dataset

In [38]:
print("Shape of Dataset:")
print(df.shape)

Shape of Dataset:
(150, 6)

# Display Column Names

In [39]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

# Step 4: Data Preprocessing

## Check Missing Values

In [10]:
print("Missing Values in Dataset:")
print(df.isnull().sum())

Missing Values in Dataset:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

# Generate Statistical Summary

In [12]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# Display Information About Dataset

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# Variable Description

| Variable Name | Description |
|---------------|-------------|
| Id | Unique identification number |
| SepalLengthCm | Length of sepal in centimeters |
| SepalWidthCm | Width of sepal in centimeters |
| PetalLengthCm | Length of petal in centimeters |
| PetalWidthCm | Width of petal in centimeters |
| Species | Type of Iris flower |

# Step 5: Check Data Types of Variables

In [17]:
print("Data Types of Variables:")
print(df.dtypes)

Data Types of Variables:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

# Check Unique Values in Categorical Variable

In [23]:
print("Unique Species Names:")
print(df['Species'].unique())

Unique Species Names:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

# Step 6: Convert Categorical Variables into Quantitative Variables

Using Label Encoding to convert Species column into numeric form.

In [40]:
# Create Label Encoder Object

le = LabelEncoder()

# Convert categorical values into numeric values

df['Species'] = le.fit_transform(df['Species'])

print("Categorical Variable Converted Successfully")

Categorical Variable Converted Successfully

# Display Dataset After Encoding

In [27]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

# Data Normalization

Normalize numerical variables using MinMaxScaler.

In [29]:
# Create Scaler Object

scaler = MinMaxScaler()

# Select Numerical Columns

numeric_columns = ['SepalLengthCm',
                   'SepalWidthCm',
                   'PetalLengthCm',
                   'PetalWidthCm']

# Apply Normalization

df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

print("Normalization Completed Successfully")

Normalization Completed Successfully

# Display Dataset After Normalization

In [41]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

# Final Data Types After Conversion

In [42]:
print(df.dtypes)

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int64
dtype: object